curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/xroar.wasm
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/dragon/images/tinydragon.png
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/d64_1.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/d64_2.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/dplus49b.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/bas13.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/extbas11.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/disk11.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/d32.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/alpha-boot-v1.0.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/alpha-basic.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/d200e_1.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/d200e_2.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/d200e_26.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/deluxe.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/coco3.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/coco3p.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/mc10.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/mx1600bas.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/mx1600extbas.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/cp400bas.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/cp400ext.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/cp450dsk.rom
curl.exe --ssl-no-revoke -O https://www.6809.org.uk/xroar/online/alice.rom
